github: csokosgeza # A te GitHub felhasználóneved, ha a GitHub Sponsors aktív
# patreon: your_patreon_username # Ha lenne Patreonod
# open_collective: your_open_collective_project
# ko_fi: your_ko_fi_username
# tidelift: your_tidelift_platform/your_package_name
# community_bridge: your_project_name
# liberapay: your_liberapay_username
# issuehunt: your_issuehunt_username
#otechie: your_otechie_username
custom: 'https://www.buymeacoffee.com/csokosgeza' # Egyedi linkek, ide mehet a Buy Me a Coffee